### ISSUE TITLE
Add option for codecheck on focal

### ISSUE THREAD

**Issue by mjcarroll** [ignition-tooling/ubuntu-bionic-ci-action#42]
Currently, we have cpplint and cppcheck completely disabled on all focal builds with a note https://github.com/ignition-tooling/action-ignition-ci/blob/f2b3848e8b6bb7a4399c17466470eb7328db61c1/entrypoint.sh#L124

As we move to drop bionic support, I believe it makes sense to attempt to turn these checks on for focal, where possible.

I have one workaround here: https://github.com/ignitionrobotics/ign-math/pull/296 by running it in the `after_make.sh` script specifically for focal.

I know historically `cppcheck` causes the most issues. Since `cpplint` and `cppcheck` are separate make targets, we may be able to turn `cpplint` on everywhere and scope the option to just `cppcheck`

**Comment by scpeters** [comment]
I believe this has been fixed by #43
